theme: jekyll-theme-cayman

title: Idea Beacon
email: realideabeacon@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Idea Beacon will make your business idea become true.
  Bring your idea and talk to us!

markdown: kramdown
twitter_username: ideabeacon
github_username:  ideabeacon
